### ISSUE TITLE
Add to home screen does not appear

### ISSUE THREAD

**Issue by reidelon** [mdn/pwa-examples#14]
In firefox the button for install(Add to home screen) does not appear, I'm using Firefox 80.0.1 (64-bit) in ubuntu 18.04, I think the reason is that the beforeinstallprompt event is no firing

**Comment by chrisdavidmills** [comment]
Interesting. I'm sure this worked before when we originally updated the code.

The button doesn't seem to appear in Chrome either, at least not for me (on Android)

And also the automatic a2hs button that is supposed to appear at the top of Firefox for Android does not seem to appear either!

Have you had any luck with these?

**Comment by GameDevZach** [comment]
Umm... did the event get removed? This seems like a bug, as it should at least show the range of versions where it was supported, right? https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent
It works in Chrome for me on Android, but the button is gone in Firefox

**Comment by reidelon** [comment]
Seems like beforeinstallprompt  has no support in firefox.

**Comment by im-ghost** [comment]
The example giving my mdn seems to have the mobile app features,when I long press it a tooltip will show for freeze, uninstall and share,but that didn't happen for my own example,I wonder why?

**Comment by Rumyra** [comment]
This won't show up in Firefox desktop because it doesn't support install for pwas 👍
