### ISSUE TITLE
Cycletracker service worker not working

### ISSUE THREAD

**Issue by Arei1126** [mdn/pwa-examples#34]
When I open /service_workers/index.html,  I always see an error "sw.js:1 Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed" in console, and it does not  cache any data.

 Probably, the name of  file name in APP_STATIC_RESOURCES is wrong(styles.css -> style.css).

**Comment by bsmth** [comment]
Thanks a lot for reporting @Arei1126 - this should be fixed now in the linked PRs. I've tried this out locally with Chrome and seems to work as expected:

![image](https://github.com/mdn/pwa-examples/assets/43580235/197b1073-d027-4a3c-9d59-52a33a61bdc2)
