### ISSUE TITLE
Why not use a JSON file for the manifest?

### ISSUE THREAD

**Issue by redrockvp** [mdn/pwa-examples#4]
It seems strange to me that the extension for the file needs to be `.webmanifest` when there are already a ton of sites with all the same metadata as is required, but in their `manifest.json` files. Are `.webmanifest` and `.json` interchangeable for this to work? if not, I think they should be as you'd be causing duplication of files.

**Comment by chrisdavidmills** [comment]
```.webmanifest``` is the extension recommended by the spec for new applications, see https://w3c.github.io/manifest/#media-type-registration.

However, I think it is a good point that you wouldn't want unnecessary duplication if you've already got compatible manifests available. I've not tested if ```.json``` will still work. We should do at some point and update the associated docs to talk about this.

**Comment by redrockvp** [comment]
Yeah, I think it might be worth mentioning in the docs.

From my testing, it seems like you can use either file extension.

Example site: https://www.gatsbyjs.org
This site uses a `.json` file generated by the `gatsby-plugin-manifest` and `gatsby-plugin-offline` plugins

**Comment by chrisdavidmills** [comment]
I've tested it again, and sure enough it works.

I've added details of this at:

* https://developer.mozilla.org/en-US/Apps/Progressive/Add_to_home_screen#How_do_you_make_an_app_A2HS-ready
* https://developer.mozilla.org/en-US/docs/Web/Manifest#Deploying_a_manifest_with_the_link_tag

It was already mentioned at https://developer.mozilla.org/en-US/Apps/Progressive/Installable_PWAs
