### ISSUE TITLE
A2HS bug on desktop

### ISSUE THREAD

**Issue by photopea** [mdn/pwa-examples#8]
I think there is some bug in your A2HS demo. It does not show any Add to Homescreen button in the latest Firefox for desktop. Not even in the latest Chrome.

**Comment by chrisdavidmills** [comment]
Hi there,

This wasn't a bug exactly; it's just that PWAs require extra steps to be installable on Desktop, and the relevant functionality is only available in Chrome currently. I've investigated this, updated our example to include the necessary code, and written up my findings here:

https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Add_to_home_screen#A2HS_on_desktop
